channels:
  - anaconda
  - defaults
dependencies:
  - pip=23.3=py38hca03da5_0
  - pip:
      - easyocr==1.7.1
      - ninja==1.11.1.1
      - opencv-python==4.8.0.74
      - opencv-python-headless==4.8.0.74
      - pyclipper==1.3.0.post5
      - pydot==1.4.2
      - python-bidi==0.4.2
      - shapely==2.0.2
      - thop==0.1.1-2209072238