channels:
  - anaconda
  - defaults
dependencies:
  - pip=23.3
  - ffmpeg=4.2.2
  - keras=2.11.0
  - opencv=4.6.0
  - scikit-image=0.19.3
  - scikit-learn=1.3.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.11.0
  - tensorflow-base=2.11.0
  - tensorflow-estimator=2.11.0
  - tensorflow-metadata=0.14.0
  - torchvision=0.15.2
  - pip:
      - easyocr==1.7.1
      - ninja==1.11.1.1
      - opencv-python==4.8.0.74
      - opencv-python-headless==4.8.0.74
      - pyclipper==1.3.0.post5
      - pydot==1.4.2
      - python-bidi==0.4.2
      - shapely==2.0.2
      - thop==0.1.1-2209072238
      - ultralytics